name: ReleaseCI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
      - uses: actions/checkout@v2
        run: |
          docker build -t temp/temp .
          docker create temp/temp --name pytest$GITHUB_RUN_NUMBER 
          docker run -it --name pytest$GITHUB_RUN_NUMBER -d temp/temp
          docker cp pytest$GITHUB_RUN_NUMBER:./app/allure-report/results.zip ./
          docker rm pytest$GITHUB_RUN_NUMBER --force
          docker rmi temp/temp --force
          ls
          mkdir publish
          unzip results.zip -d ./publish
          ls ./publish
#      - name: Deploy ðŸš€
#      - uses: JamesIves/github-pages-deploy-action@v4.2.2
#        with:
#          branch: main # The branch the action should deploy to.
#          folder: publish # The folder the action should deploy.